apiVersion: v1
kind: Pod
metadata:
  name: greeter
spec:
  containers:
    - image: "mfarsikov/greeter:1.1.1"
      name: greeter
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /ping
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources:
        requests:
          cpu: 0.25
          memory: 500M
  volumes:
    - name: "kuard-data"
      nfs:
        server: 10.116.93.178
        path: /nfsData
