apiVersion: v1
kind: Pod
metadata:
  name: greeter
  labels:
    app: greeter
spec:
  containers:
    - image: "mfarsikov/greeter:1.2.4"
      name: greeter
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /ping
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources:
        requests:
          cpu: 0.25
          memory: 500M
  volumes:
    - name: "kuard-data"
      hostPath:
        path: "/var/lib/kuard"
