apiVersion: v1
kind: Pod
metadata:
  name: greeter
spec:
  containers:
    - image: "mfarsikov/greeter:1.0.0"
      name: greeter
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
