apiVersion: v1
kind: Pod
metadata:
  name: greeter
spec:
  containers:
    - image: "mfarsikov/greeter:1.0.0"
      name: greeter
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /greeting
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources:
        requests:
          cpu: 0.25
          memory: 500M